#!/usr/bin/env python3

import sys
from PIL import Image
from pathlib import Path

try:
    path = Path(sys.argv[1])
    img = Image.open(path)
    img.save(path.with_suffix(".png"))
except Exception:
    print("Please provide a valid image")
